---
- name: Create config file for db
  template:
    src:  "{{ env_file }}.jinja2"
    dest: "/opt/{{ service }}/config/{{ env_file }}"
- name: Start Container
  docker_container:
    name: "{{ service }}"
    image: "{{ image_name }}"
    recreate: yes
    ports:
      - "{{ web_port }}:{{ web_port }}"
    volumes:
      "/opt/{{ service }}/config/{{ env_file }}:{{ container_path }}/Flask/{{ env_file }}"
    state:
      started