---
- name: Pre Tasks
  hosts: "{{ service }}"
  gather_facts: false
  pre_tasks:
    #- local_action: wait_for port=22 host={% if ansible_ssh_host is defined %}{{ ansible_ssh_host }}{% else %}{{ inventory_hostname }}{% endif %}
    - raw: timedatectl  set-timezone Asia/Jerusalem && ntpdate ntp.ubuntu.com && apt update && apt install -y python-pip
    - setup:

- name: "Deploy {{ service }}"
  hosts:  "{{ service }}"
  roles:
    - { role: roles/common}
    - { role: "roles/{{ service }}"}